### ISSUE TITLE
upload

### ISSUE THREAD

**Issue by prathamitilve** [Q-Division-2018-2019/Team-13#5]
upload a pic

**Comment by prathamitilve** [comment]
![new doc 2019-02-12 22 23 15_1](https://user-images.githubusercontent.com/46914317/52654339-c6593880-2f17-11e9-8e80-4931b827d3bb.jpg)

**Comment by Karishma264** [comment]
![screenshot_2019-02-17-19-16-46-907_com microsoft office word](https://user-images.githubusercontent.com/46923763/52914081-122a2a00-32ea-11e9-905e-fed48525e496.png)

**Comment by Karishma264** [comment]
![screenshot_2019-02-17-19-17-57-278_com microsoft office word](https://user-images.githubusercontent.com/46923763/52914088-23733680-32ea-11e9-9ccb-014d893862e1.png)

**Comment by prathamitilve** [comment]
![Screenshot_2019-04-23 How to wire to Arduino Mega](https://user-images.githubusercontent.com/46914317/56559430-49a1a500-65bf-11e9-8e0c-47cc8995c164.png)
