### ISSUE TITLE
PIC 

### ISSUE THREAD

**Issue by prathamitilve** [Q-Division-2018-2019/Team-13#6]
PIC

**Comment by prathamitilve** [comment]
![new doc 2019-02-12 23 05 51_1](https://user-images.githubusercontent.com/46914317/52656759-0242cc80-2f1d-11e9-9f40-976b2eb59724.jpg)

**Comment by prathamitilve** [comment]
![new doc 2019-02-13 08 16 53_1](https://user-images.githubusercontent.com/46914317/52683952-88d1cb00-2f6a-11e9-9287-9beb9cc097d7.jpg)

**Comment by shwetakamagond** [comment]
![new doc 2019-02-13 08 42 26_1](https://user-images.githubusercontent.com/46950344/52684698-15ea3500-2f15-11e9-8750-c969ed11e7a6.jpg)

**Comment by prathamitilve** [comment]
![new doc 2019-02-17 09 00 34_1](https://user-images.githubusercontent.com/46914317/52908018-019a9500-3293-11e9-97e3-1b836f4e85ec.jpg)

**Comment by Karishma264** [comment]
![screenshot_2019-02-18-10-53-57-187_com microsoft office word](https://user-images.githubusercontent.com/46923763/52929826-f5363b00-336b-11e9-88ee-7c57ebdda051.png)

**Comment by Karishma264** [comment]
![new doc 2019-02-18 10 59 08_1](https://user-images.githubusercontent.com/46923763/52929944-77befa80-336c-11e9-87ba-9470aad516f4.jpg)

**Comment by prathamitilve** [comment]
![Screenshot_2019-04-23 How to wire to Arduino Mega](https://user-images.githubusercontent.com/46914317/56553568-8d3ee380-65ac-11e9-89c5-6b8541361cba.png)
